version: "3.7"
services:
  api_service:
    build: .
    restart: always
    command:
      - java -jar build/libs/ecollege-0-0.1.jar
    volumes:
      - ./api-service-volume:/main-app
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    volumes:
      - ./mongodb-vollum:/data/db
      - ./mongodb-config:/data/configdb
    restart: always
    ports:
      - 27017:27017